Controllers/DetailsAjaxController.cs
using MVC_Hospitales.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Hospitales.Controllers
{
    public class DetailsAjaxController : Controller
    {
        ModeloHospital modelo = new ModeloHospital();

        public PartialViewResult DoctorFilter(String hospCod)
        {
            IQueryable<DOCTOR> doctores = modelo.GetDoctores(hospCod);

            if (doctores.Count() == 0)
            {
                return PartialView("_DetallesDoctores");
            }
            else
            {
                return PartialView("_DetallesDoctores", doctores);
            }
        }

        public PartialViewResult PlantillaFilter(String hospCod)
        {
            IQueryable<PLANTILLA> plantilla = modelo.GetPlantilla(hospCod);

            if (plantilla.Count() == 0)
            {
                return PartialView("_DetallesPlantilla");
            }
            else
            {
                return PartialView("_DetallesPlantilla", plantilla);
            }
        }

        public PartialViewResult SalaFilter(String hospCod)
        {
            IQueryable<SALA> sala = modelo.GetSalas(hospCod);

            if (sala.Count() == 0)
            {
                return PartialView("_DetallesSalas");
            }
            else
            {
                return PartialView("_DetallesSalas", sala);
            }
        }
    }
}

Controllers/HospitalesController.cs
using MVC_Hospitales.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Hospitales.Controllers
{
    public class HospitalesController : Controller
    {
        ModeloHospital modelo = new ModeloHospital();

        public ActionResult VistaHospitales()
        {
            IQueryable<HOSPITAL> listaHospitales = modelo.GetHospitals();

            return View(listaHospitales);
        }

        public ActionResult VistaDetalles(String hospCod, String hospNom)
        {
            ViewBag.Nombre = hospNom;

            HOSPITAL hospital = modelo.GetHospDetails(hospCod);

            return View(hospital);
        }
    }
}

Views/Hospitales/VistaDetalles.cshtml
@{
    ViewBag.Title = "VistaDetalles";
}
@using MVC_Hospitales.Models
@model HOSPITAL


<section class="container d-flex flex-column justify-content-center">

    <div class="hospInfo d-flex flex-row mt-5 mb-5 pt-5 pb-5 w-75 mx-auto">
        <div class="col-4 me-4">
            <img class="img-fluid rounded-3 object-fit-cover" src="~/Images/Hospitals/@Model.LINK_IMAGEN" alt="Imágen @Model.NOMBRE" loading="lazy" />
        </div>
        <div class="col-8 d-flex flex-column justify-content-between">
            <div>
                <h2>Hospital @ViewBag.Nombre</h2>
                <p>@Model.DESCRIPCION</p>
            </div>
            <div class="d-flex flex-column justify-content-end align-items-end">
                <a class="btn btn-primary me-5" href="VistaHospitales">Volver</a>
            </div>
        </div>
    </div>


    <div class="accordion">
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingOne">
                @using (Ajax.BeginForm("DoctorFilter", "DetailsAjax", new { hospCod = Model.HOSPITAL_COD }, new AjaxOptions
                {
                    HttpMethod = "POST",
                    UpdateTargetId = "docView",
                    InsertionMode = InsertionMode.Replace
                }))
                {
                    <button class="accordion-button collapsed fw-bold" name="@Model.HOSPITAL_COD" type="submit" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
                        EQUIPO MÉDICO
                    </button>
                }
            </h2>
            <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse">
                <div class="accordion-body">
                    <div id="docView" class="accordion-body"></div>
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingTwo">
                @using (Ajax.BeginForm("PlantillaFilter", "DetailsAjax", new { hospCod = Model.HOSPITAL_COD }, new AjaxOptions
                {
                    HttpMethod = "POST",
                    UpdateTargetId = "planView",
                    InsertionMode = InsertionMode.Replace
                }))
                {
                    <button class="accordion-button collapsed fw-bold" name="@Model.HOSPITAL_COD" type="submit" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                        PLANTILLA
                    </button>
                }
            </h2>
            <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
                <div class="accordion-body">
                    <div id="planView" class="accordion-body"></div>
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingThree">
                @using (Ajax.BeginForm("SalaFilter", "DetailsAjax", new { hospCod = Model.HOSPITAL_COD }, new AjaxOptions
                {
                    HttpMethod = "POST",
                    UpdateTargetId = "salaView",
                    InsertionMode = InsertionMode.Replace
                }))
                {
                    <button class="accordion-button collapsed fw-bold" name="@Model.HOSPITAL_COD" type="submit" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                        SALAS
                    </button>
                }
            </h2>
            <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
                <div class="accordion-body">
                    <div id="salaView" class="accordion-body"></div>
                </div>
            </div>
        </div>
    </div>

</section>


@section scripts
{
    @Scripts.Render("~/Scripts/jquery-3.7.0.js")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")
}

Views/Hospitales/VistaHospitales.cshtml
@{
    ViewBag.Title = "VistaHospitales";
}
@using MVC_Hospitales.Models
@model IQueryable<HOSPITAL>
<link href="@Url.Content("~/SASS/main.css")" rel="stylesheet" />


<h2 class="text-center mt-5 text-primary">Nuestros Hospitales</h2>

@if (Model != null)
{
    <div class="container mb-5">
        <div class="container px-4 py-5 " id="custom-cards">
            <div class="row row-cols-1 row-cols-lg-2 align-items-stretch g-5 py-1">
                @foreach (var hosp in Model)
                {
                    <div class="col">
                        <div class="card card-cover h-100 overflow-hidden rounded-4" id="cards">
                            <div class="d-flex flex-column h-100 p-3 pb-3 text-white text-shadow-1">
                                <img class="img-card-top hospImg object-fit-cover" src="~/Images/Hospitals/@hosp.LINK_IMAGEN" alt="Imágen del hospital @hosp.NOMBRE" loading="lazy">
                                <div class="hospInfo">
                                    <div class="d-flex flex-column mt-auto">
                                        <div>
                                            <h2>Hospital @hosp.NOMBRE</h2>
                                        </div>
                                        <div class="d-flex flex-column mb-4">
                                            <p class="card-text mt-2 mb-1">@hosp.DIRECCION</p>
                                            <p class="card-text mb-3">Contacto: @hosp.TELEFONO</p>
                                        </div>
                                        @Html.ActionLink("Más detalles", "VistaDetalles", "Hospitales", new { hospCod = hosp.HOSPITAL_COD, hospNom = hosp.NOMBRE }, new { @class = "btn btn-primary" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
}


else
{
    <h3 class="hospError">No se han podido mostrar los hospitales</h3>
}