Controllers/DetailsAjaxController.cs
using MVC_Hospitales.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Hospitales.Controllers
{
    public class DetailsAjaxController : Controller
    {
        ModeloHospital modelo = new ModeloHospital();

        public PartialViewResult DoctorFilter(String hospCod)
        {
            IQueryable<DOCTOR> doctores = modelo.GetDoctores(hospCod);

            if (doctores.Count() == 0)
            {
                return PartialView("_DetallesDoctores");
            }
            else
            {
                return PartialView("_DetallesDoctores", doctores);
            }
        }

        public PartialViewResult PlantillaFilter(String hospCod)
        {
            IQueryable<PLANTILLA> plantilla = modelo.GetPlantilla(hospCod);

            if (plantilla.Count() == 0)
            {
                return PartialView("_DetallesPlantilla");
            }
            else
            {
                return PartialView("_DetallesPlantilla", plantilla);
            }
        }

        public PartialViewResult SalaFilter(String hospCod)
        {
            IQueryable<SALA> sala = modelo.GetSalas(hospCod);

            if (sala.Count() == 0)
            {
                return PartialView("_DetallesSalas");
            }
            else
            {
                return PartialView("_DetallesSalas", sala);
            }
        }
    }
}

Controllers/GestionController.cs
using MVC_Hospitales.Models;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using iTextSharp.text.pdf;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf.parser;

namespace MVC_Hospitales.Controllers
{
    public class GestionController : Controller
    {
        ModeloHospital modelo = new ModeloHospital();

        public ActionResult EliminarDoc(String id)
        {
            modelo.EliminarDoctores(id);

            return RedirectToAction("VistaDetalles");
        }


        public ActionResult InformeDoctor(String docNo)
        {
            DOCTOR doctor = modelo.GetInfoDoctor(docNo);
            Document docpdf = new Document(PageSize.LETTER);

            String ruta = HttpContext.Server.MapPath("/PDF/");

            ruta = ruta + "informe" + docNo.ToString() + ".pdf";

            if (System.IO.File.Exists(ruta))
            {
                return File(ruta, "application/pdf");
            }
            else
            {
                PdfWriter writer = PdfWriter.GetInstance(docpdf, new FileStream(ruta, FileMode.Create));

                docpdf.AddTitle("Informe del empleado: " + doctor.APELLIDO);
                docpdf.AddCreator("ALCES");

                docpdf.Open();

                iTextSharp.text.Font _standardFont = new iTextSharp.text.Font(iTextSharp.text.Font.FontFamily.HELVETICA, 11, iTextSharp.text.Font.NORMAL, BaseColor.BLACK);

                docpdf.Add(new Paragraph("Informe del empleado: " + doctor.APELLIDO));
                docpdf.Add(new Paragraph(DateTime.Now.ToLongDateString()));

                docpdf.Add(Chunk.NEWLINE);

                PdfPTable tabla = new PdfPTable(3);
                tabla.WidthPercentage = 100;

                PdfPCell colapellido = new PdfPCell(new Phrase("APELLIDO", _standardFont));
                colapellido.BorderWidth = 0;
                colapellido.BorderWidthBottom = 0.75f;

                PdfPCell colespecialidad = new PdfPCell(new Phrase("ESPECIALIDAD", _standardFont));
                colespecialidad.BorderWidth = 0;
                colespecialidad.BorderWidthBottom = 0.75f;

                PdfPCell colsalario = new PdfPCell(new Phrase("SALARIO", _standardFont));
                colsalario.BorderWidth = 0;
                colsalario.BorderWidthBottom = 0.75f;

                tabla.AddCell(colapellido);
                tabla.AddCell(colespecialidad);
                tabla.AddCell(colsalario);

                colapellido = new PdfPCell(new Phrase(doctor.APELLIDO, _standardFont));
                colapellido.BorderWidth = 0;

                colespecialidad = new PdfPCell(new Phrase(doctor.ESPECIALIDAD, _standardFont));
                colespecialidad.BorderWidth = 0;

                colsalario = new PdfPCell(new Phrase(doctor.SALARIO.ToString() + "€", _standardFont));
                colsalario.BorderWidth = 0;

                tabla.AddCell(colapellido);
                tabla.AddCell(colespecialidad);
                tabla.AddCell(colsalario);

                docpdf.Add(tabla);

                docpdf.Close();
                writer.Close();

                return File(ruta, "application/pdf");
            }
        }

        public ActionResult InformePersonal(String empNo)
        {
            PLANTILLA plantilla = modelo.GetInfoPlantilla(empNo);
            Document docpdf = new Document(PageSize.LETTER);

            String ruta = HttpContext.Server.MapPath("/PDF/");

            ruta = ruta + "informe" + empNo.ToString() + ".pdf";

            if (System.IO.File.Exists(ruta))
            {
                return File(ruta, "application/pdf");
            }
            else
            {
                PdfWriter writer = PdfWriter.GetInstance(docpdf, new FileStream(ruta, FileMode.Create));

                docpdf.AddTitle("Informe del empleado: " + plantilla.APELLIDO);
                docpdf.AddCreator("Ejemplo MVC");

                docpdf.Open();

                iTextSharp.text.Font _standardFont = new iTextSharp.text.Font(iTextSharp.text.Font.FontFamily.HELVETICA, 11, iTextSharp.text.Font.NORMAL, BaseColor.BLACK);

                docpdf.Add(new Paragraph("Informe del empleado: " + plantilla.APELLIDO));
                docpdf.Add(new Paragraph(DateTime.Now.ToLongDateString()));

                docpdf.Add(Chunk.NEWLINE);

                PdfPTable tabla = new PdfPTable(4);
                tabla.WidthPercentage = 100;

                PdfPCell colapellido = new PdfPCell(new Phrase("APELLIDO", _standardFont));
                colapellido.BorderWidth = 0;
                colapellido.BorderWidthBottom = 0.75f;

                PdfPCell colfuncion = new PdfPCell(new Phrase("FUNCIÓN", _standardFont));
                colfuncion.BorderWidth = 0;
                colfuncion.BorderWidthBottom = 0.75f;

                PdfPCell colturno = new PdfPCell(new Phrase("TURNO", _standardFont));
                colturno.BorderWidth = 0;
                colturno.BorderWidthBottom = 0.75f;

                PdfPCell colsalario = new PdfPCell(new Phrase("SALARIO", _standardFont));
                colsalario.BorderWidth = 0;
                colsalario.BorderWidthBottom = 0.75f;

                tabla.AddCell(colapellido);
                tabla.AddCell(colfuncion);
                tabla.AddCell(colturno);
                tabla.AddCell(colsalario);

                colapellido = new PdfPCell(new Phrase(plantilla.APELLIDO, _standardFont));
                colapellido.BorderWidth = 0;

                colfuncion = new PdfPCell(new Phrase(plantilla.FUNCION, _standardFont));
                colfuncion.BorderWidth = 0;

                colturno = new PdfPCell(new Phrase(plantilla.T, _standardFont));
                colturno.BorderWidth = 0;

                colsalario = new PdfPCell(new Phrase(plantilla.SALARIO.ToString() + "€", _standardFont));
                colsalario.BorderWidth = 0;

                tabla.AddCell(colapellido);
                tabla.AddCell(colfuncion);
                tabla.AddCell(colturno);
                tabla.AddCell(colsalario);

                docpdf.Add(tabla);

                docpdf.Close();
                writer.Close();

                return File(ruta, "application/pdf");
            }
        }
    }
}

Views/DetailsAjax/_DetallesDoctores.cshtml
@using MVC_Hospitales.Models
@model IQueryable<DOCTOR>

@Scripts.Render("~/Scripts/jquery-3.7.0.slim.min.js")
@Scripts.Render("~/Scripts/umd/popper.min.js")
@Scripts.Render("~/Scripts/bootstrap.bundle.min.js")

<link href="@Url.Content("~/SASS/main.css")" rel="stylesheet" />

@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    APELLIDO
                </th>
                <th>
                    ESPECIALIDAD
                </th>
                <th>
                    SALARIO
                </th>
                <th>
                    ACCIONES
                </th>
            </tr>
        </thead>

        @foreach (var doc in Model)
        {
            <tbody>
                <tr>
                    <td class="align-middle">
                        @doc.APELLIDO
                    </td>
                    <td class="align-middle">
                        @doc.ESPECIALIDAD
                    </td>
                    <td class="align-middle">
                        @doc.SALARIO €.
                    </td>
                    <td class="align-middle">
                        <div class="dropdown">
                            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Acciones</button>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Descargar informe", "InformeDoctor", "Gestion", new { docNo = doc.DOCTOR_NO }, new { @class = "dropdown-item", target = "_blank" })</li>
                                <li><a class="dropdown-item" href="#">Editar datos empleado</a></li>
                                <li>@Html.ActionLink("Eliminar doctor", "EliminarDoc", "Gestion", new { id = doc.DOCTOR_NO }, new { @class = "dropdown-item", onclick = $"return confirm('¿Está seguro que quiere eliminar el registro del doctor {doc.APELLIDO}?');" })</li>
                            </ul>
                        </div>
                    </td>
                </tr>
            </tbody>
        }

    </table>
}

else
{
    <h2 style="color:red">No existe equipo médico en este hospital</h2>
}

Views/DetailsAjax/_DetallesPlantilla.cshtml
@using MVC_Hospitales.Models
@model IQueryable<PLANTILLA>

<link href="@Url.Content("~/SASS/main.css")" rel="stylesheet" />

@if (Model != null)
{

    <table class="table">
        <thead>
            <tr>
                <th>
                    APELLIDO
                </th>
                <th>
                    FUNCIÓN
                </th>
                <th>
                    TURNO
                </th>
                <th>
                    SALARIO
                </th>
                <th>
                    ACCIONES
                </th>
            </tr>
        </thead>

        @foreach (var plan in Model)
        {
            <tbody>
                <tr>
                    <td class="align-middle">
                        @plan.APELLIDO
                    </td>
                    <td class="align-middle">
                        @plan.FUNCION
                    </td>
                    <td class="align-middle">
                        @plan.T
                    </td>
                    <td class="align-middle">
                        @plan.SALARIO €.
                    </td>
                    <td class="align-middle">
                        <div class="dropdown">
                            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Acciones</button>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Descargar informe", "InformeEmpleado", "Gestion", new { docNo = plan.EMPLEADO_NO }, new { @class = "dropdown-item", target = "_blank" })</li>
                                <li><a class="dropdown-item" href="#">Editar datos empleado</a></li>
                                <li>@Html.ActionLink("Eliminar empleado", "EliminarEmp", "Gestion", new { id = plan.EMPLEADO_NO }, new { @class = "dropdown-item", onclick = $"return confirm('¿Está seguro que quiere eliminar el registro del empleado {plan.APELLIDO}?');" })</li>
                            </ul>
                        </div>
                    </td>
                </tr>
            </tbody>
        }

    </table>
}

else
{
    <h2 style="color:red">No existe personal médico en este hospital</h2>
}

Views/DetailsAjax/_DetallesSalas.cshtml
@using MVC_Hospitales.Models
@model IQueryable<SALA>

<link href="@Url.Content("~/SASS/main.css")" rel="stylesheet" />

@if (Model != null)
{

    <table class="table">
        <thead>
            <tr>
                <th>
                    TIPOS DE CUIDADOS (ESPECIALIDAD)
                </th>
                <th>
                    CAMAS DISPONIBLES
                </th>
            </tr>
        </thead>

        @foreach (var sala in Model)
        {
            <tbody>
                <tr>
                    <td class="align-middle">
                        @sala.NOMBRE
                    </td>
                    <td class="align-middle">
                        @sala.NUM_CAMA
                    </td>
                </tr>
            </tbody>
        }

    </table>
}

else
{
    <h2 style="color:red">No existe personal médico en este hospital</h2>
}